# Generated by Django 4.2.25 on 2025-10-31 06:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_at', models.DateField(default=1970)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publish_at', models.DateTimeField(default=datetime.datetime(2025, 10, 31, 6, 27, 47, 771902, tzinfo=datetime.timezone.utc))),
                ('author', models.ManyToManyField(to='polls.author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.publisher')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='publisher',
            field=models.ManyToManyField(to='polls.publisher'),
        ),
    ]
