# Generated by Django 4.2.25 on 2025-10-31 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publish_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='start_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
