# Generated by Django 4.2.25 on 2025-10-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_books_publish_at_alter_publisher_start_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['title']},
        ),
    ]
