# Generated by Django 4.2.25 on 2025-10-31 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_publisher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['title']},
        ),
    ]
