# Generated by Django 4.2.25 on 2025-11-02 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('data', models.TextField()),
                ('data_time', models.DateField(default=django.utils.timezone.now)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
