# Generated by Django 4.2.25 on 2025-11-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['data_time'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
